### ISSUE TITLE
Strange chwb2 borders

### ISSUE THREAD

**Issue by Barbaross93** [wmutils/opt#48] opened 2020-07-31 13:58 UTC
Hello,

I've recently updated to the latest git version of chwb2 and I've noticed that for windows that have some transparent property now get transparent borders with an incorrect color for the inner border. Before updating, the borders would simply be solid of whatever color I set them to be in my bspwmrc. If I kill picom, I get the expected behavior of two window border colors. I guess I was wondering if anyone knew if there was a proper setting in picom to ignore transparent borders? I've attached a screenshot showing the current behavior while picom is running. The window on the left has the unusual behavior while the expected behavior is on the right.

![1596203595](https://user-images.githubusercontent.com/57952969/89041643-41452780-d335-11ea-8b60-61d654dddf55.png)

Here's another screenshot showing the same screen but picom killed. The borders are now behaving as expected.

![1596203749](https://user-images.githubusercontent.com/57952969/89041907-a6008200-d335-11ea-95d2-8b6732925ddd.png)

**Comment by z3bra** [comment] 2020-07-31 19:12
See https://github.com/wmutils/opt/pull/47

What you're describing is actually a feature. `chwb2` used to use the
depth of the root window to draw the borders, rather than the client's.

This means that if a window is capable of transparency, the border should
act the same.

What you can do is try to "force" the transparency value by specifying
something like:

	chwb2 -I '0xff123456'

Where "ff" is fully opaque.

**Comment by Barbaross93** [comment] 2020-07-31 20:02
Thanks for the suggestion! I've tried setting it to fully opaque, but the
border ends up being a solid color. In fact, I can only go up until 49%
opacity before it suddenly always give a solid border at 50% and above. I
do notice the border becoming more and more opaque going from 00 (0%) to 7d
(49%), but it doesn't hit fully opaque (obviously).

With a little more testing, it turns out that it's not flipping the border
solid colored, nothing happens when I change the opacity past 49%. I'm
assuming that the solid color is just the result of the WM (bspwm in this
case) when I focused the window.

**Comment by z3bra** [comment] 2020-07-31 21:00
Then I guess it's just up to your compositor to render the border transparency. When playing with another WM and transparency, I found that some color change the way the alpha channel is rendered, in such a way that 0x000000 is fully transparent, whill 0xffffff is totally opaque.

Some compositor, like compton, have a flag to se the border opacity, and there's not much you can do to change this.

To be fair, I neither use chwb2 nor a compositor, so I am not sure what behavior should be expected.

**Comment by Barbaross93** [comment] 2020-08-01 12:33
Hmm, bummer. Thanks for suggestions at least! I'll mess around with picom's settings and see if I can get anything to work. @jwijenbergh I assume everything is working for you? Do you use picom/compton? I'd be curious to see your config file.

**Comment by Barbaross93** [comment] 2020-08-01 12:52
Small update: apparently setting the alpha value to 50% in above with chwb2  when picom is not running also doesn't work; seems to imply that there is either a problem with chwb2 or bspwm

**Comment by jwijenbergh** [comment] 2020-08-01 13:36
> Hmm, bummer. Thanks for suggestions at least! I'll mess around with picom's settings and see if I can get anything to work. @jwijenbergh I assume everything is working for you? Do you use picom/compton? I'd be curious to see your config file.

I do indeed use picom and do have this issue on certain applications such as zathura. It also happens for certain terminal emulators. However, using `st` without the transparency patch works for me. You can try reverting #47 and see if that works better for you (but then the borders might not work at all). 

Forcing transparency also does not seem to work with chwb2 for me. I will investigate this and see if this can be fixed with picom

**Comment by jwijenbergh** [comment] 2020-08-01 13:47
> Hmm, bummer. Thanks for suggestions at least! I'll mess around with picom's settings and see if I can get anything to work. @jwijenbergh I assume everything is working for you? Do you use picom/compton? I'd be curious to see your config file.

I do not use transparency, so this is not a problem for me. See the following picom settings:
```
inactive-opacity = 1;
active-opacity = 1;
frame-opacity = 1;
```
If you indeed use transparency, there can be some problems (forcing transparency prefix 0xff doesn't seem to work either). Is that zathura you're using on the left? I will investigate this further

update:

Even with transparency turned off, I see issues with applications such as zathura and some emulators like alacritty (exactly like your screenshot). You can notice that this issue is not there when you have only instances of e.g. st without the alpha patch. I will see what is the best solution here, as going back to drawing with the root window causes the border to not draw at all.

**Comment by jwijenbergh** [comment] 2020-08-01 14:34
Alright the following diff works perfectly:

```diff
diff --git a/chwb2.c b/chwb2.c
index db75a0f..1ee3554 100644
--- a/chwb2.c
+++ b/chwb2.c
@@ -59,6 +59,11 @@ int is; /* inner size  */
 	if (is + os > geom->border_width)
 		warnx("warning: pixmap is greater than border size");
 
+	oc |= 0xff << 24;
+	os |= 0xff << 24;
+	ic |= 0xff << 24;
+	is |= 0xff << 24;
+
 	w = (short)geom->width;
 	h = (short)geom->height;
 	b = (unsigned short)is+os;
```

This basically sets the border color to ff (no transparency). Do we want to have separate command line options to set the specified border opacity @z3bra ? This explains why forcing the border through the command line options doesn't work as the transparency is not shifted by 24 if e.g. the color is 0x111111 and we set it to 0xff111111

**Comment by Barbaross93** [comment] 2020-08-01 14:35
Thanks for responding! Indeed, that is zathura in the screenshot. I tried disabling transparency/opacity in picom and the problem persists. I see a similar effect with zoom as well, but I haven't tried other programs with known alpha windows. Urxvt has a color depth option that when set to 32 I see the problem, but it stops when I revert it back to 24. 

update: I'll try your patch, just saw it as I posted this reply!

**Comment by jwijenbergh** [comment] 2020-08-01 14:41
> Thanks for responding! Indeed, that is zathura in the screenshot. I tried disabling transparency/opacity in picom and the problem persists. I see a similar effect with zoom as well, but I haven't tried other programs with known alpha windows. Urxvt has a color depth option that when set to 32 I see the problem, but it stops when I revert it back to 24.
> 
> update: I'll try your patch, just saw it as I posted this reply!

no problem! Sorry for editing and posting my comments a bunch of times, I was testing and posting as I went along haha

**Comment by Barbaross93** [comment] 2020-08-01 15:05
No problem! Your patch works flawlessly! Hopefully we will hear from @z3bra soon. It does make sense to add a command line option. However, picom does have the frame-opacity option, so it may not be needed (it works with your patch!).

**Comment by jwijenbergh** [comment] 2020-08-01 15:11
> No problem! Your patch works flawlessly! Hopefully we will hear from @z3bra soon. It does make sense to add a command line option. However, picom does have the frame-opacity option, so it may not be needed (it works with your patch!).

Oh that makes a lot of sense then to just leave it as my patch and the opacity can then always be changed with picom. I will make a pr for the patch if @z3bra agrees

**Comment by z3bra** [comment] 2020-08-01 15:40
Given that the previous patch enabled transparency, that would be counter productive to then reset the alpha channel to 0xff. We'd better revert the previous patch in this case !

I wouldn't mind an option. As I said, I don't use chwb2 myself. Adding a flag for transparency would work. Maybe make it fully opaque by default, so we keep the old behavior unchanged.

**Comment by jwijenbergh** [comment] 2020-08-01 16:38
> Given that the previous patch enabled transparency, that would be counter productive to then reset the alpha channel to 0xff. We'd better revert the previous patch in this case !

Without the previous patch (#47), chwb2 does not change the border appearance when it tries to draw on an application such as zathura or alacritty (applications which handle the alpha channel, which with the updated patch now draw the incorrect opacity instead of not drawing at all). Reverted would make things worse. The way my diff now does is, is the exact same how dwm fixes the transparency issue when used in combination with the alpha patch: 
https://dwm.suckless.org/patches/alpha/dwm-fixborders-6.2.diff

By setting the alpha channel to `ff`, the border now correctly uses picom's `frame-opacity` setting. So if the compositor sets the border opacity to `0.5`, it sets it to that correctly (even thought chwb2 sets it to `ff`).

So I think how it stands right now is the correct way (with my new diff), as it is weird to have a transparent border when a user has set their opacity to 1.

On first glance it might seem counter-intuitive. But now that we are using the client's depth we need to handle opacity/transparency correctly which should be all fine with the newest diff. Now borders are drawn correctly for all applications (that I tested) and with a compositor either on or off.

**Comment by z3bra** [comment] 2020-08-05 06:07
What is the point of using the client depth then ?

**Comment by jwijenbergh** [comment] 2020-08-05 10:51
> What is the point of using the client depth then ?

I mentioned this in my last comment and #47, but I will give a more detailed explanation here.

Root depth doesn't work for terminal emulators such as termite or alacritty and some other applications.

To reproduce the issue with root depth do the following (with or without compositor):

- Open termite or alacritty
- Apply border with chwb2 -I 'ffffff' -O '282828' -i 2 -o 6 "$(pfw)" (and border is set to 8px in the wm)
- Nothing happens, the border remains the same as set by the wm

When using client's depth the border is set correctly. We do have to fix transparency (when using a compositor), which is what I have done. Please reproduce the issue with root depth to see what I mean.

**Comment by cogikyo** [comment] 2020-12-24 06:05
> Alright the following diff works perfectly:
> 
> ```diff
> diff --git a/chwb2.c b/chwb2.c
> index db75a0f..1ee3554 100644
> --- a/chwb2.c
> +++ b/chwb2.c
> @@ -59,6 +59,11 @@ int is; /* inner size  */
>  	if (is + os > geom->border_width)
>  		warnx("warning: pixmap is greater than border size");
>  
> +	oc |= 0xff << 24;
> +	os |= 0xff << 24;
> +	ic |= 0xff << 24;
> +	is |= 0xff << 24;
> +
>  	w = (short)geom->width;
>  	h = (short)geom->height;
>  	b = (unsigned short)is+os;
> ```
> 
> This basically sets the border color to ff (no transparency). Do we want to have separate command line options to set the specified border opacity @z3bra ? This explains why forcing the border through the command line options doesn't work as the transparency is not shifted by 24 if e.g. the color is 0x111111 and we set it to 0xff111111

Hello, I am using Barbarossa93's script that uses chwb2 to draw double borders and running into same issue. Zathura's borders are transparent. Looks like this worked for him, but I'm not too sure how to apply this patch. Mind telling me how? Thanks. 

![12-23-20__22:12:06](https://user-images.githubusercontent.com/59071534/103065874-811edc80-456c-11eb-84cd-4289b3f4dd25.gif)

Also seems to affect the background of Zathura, if that helps. I also tired the above suggestions relating to picom config with no luck. I'm not really sure how chwb2 works at all, so excuse my ignorance.

**Comment by Barbaross93** [comment] 2020-12-26 18:31
Hey @cullyn-inverba sorry I never got back to you on reddit. I was busy with finals and your message completely slipped past me. The best thing to do would be to make a separate file copying and pasting that patch into a `chwb2.patch` file. Then, do `patch < chwb2.patch` in the git directory (the patch file has to be in the directory as well). It should apply the patch to `chwb2.c` and you should then be able to compile it and run it. Windows with transparency properties should now have opaque borders. Try googling "how to use the patch command" or read the `patch` man page for more info.

@z3bra It's been awhile, do you have any further thoughts on this? It would be fantastic to see this merged.

**Comment by jwijenbergh** [comment] 2020-12-26 19:22
> > Alright the following diff works perfectly:
> > ```diff
> > diff --git a/chwb2.c b/chwb2.c
> > index db75a0f..1ee3554 100644
> > --- a/chwb2.c
> > +++ b/chwb2.c
> > @@ -59,6 +59,11 @@ int is; /* inner size  */
> >  	if (is + os > geom->border_width)
> >  		warnx("warning: pixmap is greater than border size");
> >  
> > +	oc |= 0xff << 24;
> > +	os |= 0xff << 24;
> > +	ic |= 0xff << 24;
> > +	is |= 0xff << 24;
> > +
> >  	w = (short)geom->width;
> >  	h = (short)geom->height;
> >  	b = (unsigned short)is+os;
> > ```
> > 
> > 
> > This basically sets the border color to ff (no transparency). Do we want to have separate command line options to set the specified border opacity @z3bra ? This explains why forcing the border through the command line options doesn't work as the transparency is not shifted by 24 if e.g. the color is 0x111111 and we set it to 0xff111111
> 
> Hello, I using Barbarossa93's script that sues chwb2 to draw double borders and running into same issue. Zathura's borders are transparent. Looks like this worked for him, but I'm not too sure how to apply this patch. Mind telling me how? Thanks.
> 
> ![12-23-20__22:12:06](https://user-images.githubusercontent.com/59071534/103065874-811edc80-456c-11eb-84cd-4289b3f4dd25.gif)
> 
> Also seems to affect the background of Zathura, if that helps. I also tired the above suggestions relating to picom config with no luck. I'm not really sure how chwb2 works at all, so excuse my ignorance.

You can use my branch https://github.com/jwijenbergh/opt/tree/fix-transparency-chwb2
Sorry I didn't see your reply before.



> Hey @cullyn-inverba sorry I never got back to you on reddit. I was busy with finals and your message completely slipped past me. The best thing to do would be to make a separate file copying and pasting that patch into a `chwb2.patch` file. Then, do `patch < chwb2.patch` in the git directory (the patch file has to be in the directory as well). It should apply the patch to `chwb2.c` and you should then be able to compile it and run it. Windows with transparency properties should now have opaque borders. Try googling "how to use the patch command" or read the `patch` man page for more info.
> 
> @z3bra It's been awhile, do you have any further thoughts on this? It would be fantastic to see this merged.

Thanks for commenting!

Indeed, hopefully @z3bra agrees so we can merge the changes. I don't really use this all the time but afaik my branch now should work as expected.

**Comment by z3bra** [comment] 2020-12-26 20:21
Let it be fantastic then !

**Comment by cogikyo** [comment] 2020-12-26 23:38
Excellent. Thanks for the help guys! Didn't use your branch @jwijenbergh, mostly because I wanted to learn how to use the patch, but I would have if it was harder than what it ended up being.

**Closed as completed** 2021-01-03 10:21 UTC
