### ISSUE TITLE
chwb2 doesn't make any effect

### ISSUE THREAD

**Issue by BillyTheMotherBoard** [wmutils/opt#41] opened 2018-11-06 22:26 UTC
Hello !
First of all, thanks for providing these tools,
while trying to get chwb2 working on bspwm I noticed that there wasn't any effect on the window, I ran this command from the man page:
`chwb2 -O 000000 -I ffff00 -i 3 -o 1`

Can you help me? As there aren't really any other example of this utility...
Thanks

**Comment by neeasade** [comment] 2018-11-07 00:10
The arguments following your example should be window IDs to draw on

**Comment by BillyTheMotherBoard** [comment] 2018-11-07 15:09
Thank you for your answer man! really appreciate that but I do not completely understand, what would be the line to put into my bspwmrc or other config file to get the double border for all types of windows, from URxvt to Firefox?

Thanks, sorry for being annoying

**Comment by z3bra** [comment] 2018-11-07 16:18
>  what would be the line to put into my bspwmrc or other config file to get the double border for all types of windows, from URxvt to Firefox?
 
There is no answer to that question because your question is incorrect.
As neasade said, `chwb2` require that you pass the window ID of the window to affect in argument. For example:
 
     chwb2 -O 000000 -I ffff00 -i 3 -o 1 0x23
 
If you want to apply that to all windows, then you have to run this command one time per window you have, or script it, like this for example:
 
     lsw | xargs -n1 chwb2 -O 000000 -I ffff00 -i 3 -o 1
 
One problem you'll have is that the borders will look bad when you move the windows. This is because the internal border is drawn using absolute coordinates from you desktop. _This is not a bug_, just the way it works. When a window move, you have to redraw the 2-border pixmap (that is how 2bwm does it).
So to answer your question, you need to find a way to run a command whenever a window move, get its window ID (hint: use `pfw`/`lsw`) and run the `chwb2` command *with the window ID as the last argument*.
 
Hope that helps, cheers

**Comment by z3bra** [comment] 2018-11-09 15:52
Closing as it is not an issue but misuse of the tool.

**Closed as completed** 2018-11-09 15:51 UTC

**Comment by BillyTheMotherBoard** [comment] 2018-11-15 21:43
Hello, well thank you for your detailed reply, sorry for this late reply but I was studying for exams...

Well it creates borders when I run this command:
` lsw | xargs -n1 chwb2 -O 000000 -I ffff00 -i 3 -o 1`

but it also throws out a bunch of "errors" maybe? Also I can't increase my double borders size...
```

chwb2: warning: pixmap is greater than border size
chwb2: warning: pixmap is greater than border size
chwb2: warning: pixmap is greater than border size
chwb2: warning: pixmap is greater than border size
chwb2: warning: pixmap is greater than border size
chwb2: warning: pixmap is greater than border size
chwb2: warning: pixmap is greater than border size
usage: chwb2 <-I color> <-O color> <-i size> <-o size> [wid...]
usage: chwb2 <-I color> <-O color> <-i size> <-o size> [wid...]
usage: chwb2 <-I color> <-O color> <-i size> <-o size> [wid...]
usage: chwb2 <-I color> <-O color> <-i size> <-o size> [wid...]
chwb2: warning: pixmap is greater than border size
xargs: unmatched single quote; by default quotes are special to xargs unless you use the -0 option
```
I'm back to you because I don't really know how to handle this output...

thanks for the high quality assistance ;)

**Comment by z3bra** [comment] 2018-11-16 00:04
`chwb2` will draw the double borders on the actual borders. It will not create them.
You need to first create the borders with `chwb`, and then use `chwb2` on them.
From your example, you want a 3px inner border and 1px outer border.
You should then create a border that is at least 4px wide with `chwb`, otherwise the border will be too small to draw the double border pixmap.

Le Vendredi 16 novembre 2018, Billy the Hustler a écrit :
> Hello, well thank you for your detailed reply, sorry for this late reply but I was studying for exams...
> 
> Well it creates borders when I run this command:
> ` lsw | xargs -n1 chwb2 -O 000000 -I ffff00 -i 3 -o 1`
> 
> but it also throws out a bunch of "errors" maybe? Also I can't increase my double borders size...
> ```
> 
> chwb2: warning: pixmap is greater than border size
> chwb2: warning: pixmap is greater than border size
> chwb2: warning: pixmap is greater than border size
> chwb2: warning: pixmap is greater than border size
> chwb2: warning: pixmap is greater than border size
> chwb2: warning: pixmap is greater than border size
> chwb2: warning: pixmap is greater than border size
> usage: chwb2 <-I color> <-O color> <-i size> <-o size> [wid...]
> usage: chwb2 <-I color> <-O color> <-i size> <-o size> [wid...]
> usage: chwb2 <-I color> <-O color> <-i size> <-o size> [wid...]
> usage: chwb2 <-I color> <-O color> <-i size> <-o size> [wid...]
> chwb2: warning: pixmap is greater than border size
> xargs: unmatched single quote; by default quotes are special to xargs unless you use the -0 option
> ```
> I'm back to you because I don't really know how to handle this output...
> 
> thanks for the high quality assistance ;)
> 
> -- 
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub:
> https://github.com/wmutils/opt/issues/41#issuecomment-43920091

-- 
-- 
Peace.
